/* export const homeObjOne = {
    id:'about',
    lightBg:false,
    lightText:true,
    lightTextDesc:true,
    topLine: 'Premium Bank',
    headline: 'unlimited Transactions with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel:'Get Started',
    imgStart: false,
    img: require('../../images/svg-1.svg').default,
    alt:'Car',
    dark:true,
    primary:true,
    darkText:false,

};
 */
export const homeObjTwo = {
    id:'discover',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine: 'Servicios',
    headline: 'Servicios',
    description: 'Ejecución de obras y reformas necesarias en el espacio que nos entregue. Ofrecemos mejoras locativas y de elementos completas. ',
    li:true,
    li2:'Remodelación de casas',
    li3:'Remodelación de apartamentos',
    li4:'Remodelación de oficinas',
    li5:'Remodelación de locales comerciales',
    li6:'Reformas locativas',
    buttonLabel:'Ir al inicio',
    imgStart: true,
    img: require('../../images/svg-3.svg').default,
    alt:'Piggybank',
    dark:false,
    primary:false,
    darkText:true,

};

export const homeObjThree = {
    id:'signup',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine: 'Contacto',
    headline: 'Contacto',
    description: 'Get access to our exclusivess app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel:'Ir al inicio',
    imgStart: false,
    li:false,
    contact:true,
    setImg:false,
    img: require('../../images/svg-7.svg').default,
    alt:'Paper',
    dark:false,
    primary:false,
    darkText:true,

};